# Generated by Django 2.0.3 on 2018-08-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20180815_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cranedevices',
            options={'managed': True, 'verbose_name_plural': 'Crane Devices'},
        ),
        migrations.AlterModelOptions(
            name='cranetypes',
            options={'managed': True, 'verbose_name': 'Crane Type', 'verbose_name_plural': 'Crane Types'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True, 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'managed': False, 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='sitecranes',
            options={'managed': True, 'verbose_name': 'Crane', 'verbose_name_plural': 'Cranes'},
        ),
        migrations.AlterModelOptions(
            name='sites',
            options={'managed': True, 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
    ]
